name: "Espressif IoT Development Framework (ESP-IDF), plus node.js and npm"
branding:
  color: red
  icon: wifi
inputs:
  command:
    description: "Command to run inside the docker container (default: builds the project)"
    default: "./create_release_zip.sh"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "/bin/bash"
    - "-c"
    - "${{inputs.command}}"
